# Installation Notes

The *MetaboMate* package is currently hosted on GitHub. Therefore, the installation is performed using the *devtools* R package. Run the following code to install first *devtools* and then *MetaboMate*:
```r
# check if devtools is already installed and if not, install it
if(!requireNamespace('devtools')){install.packages('devtools')}

# install MetaboMate
devtools::install_github('kimsche/MetaboMate')

# load the package
library('MetaboMate')
```

The package installation should not take longer than a minute (most likely much shorter, depends on your internet bandwith).
After successfull installation the last command above (``library(MetaboMate)``) returns no error message. See the sections below for additional help if an installation error came up. Scroll further down for a list of tutorials and workflows.

&nbsp;

&nbsp;

### Additional Installation Guidance for R Starters

&nbsp;

#### Warnings vs. Errors
During the installation process there might come up **warning messages** (the most common one is: *unknown time zone*). Warning messages are not a problem and can be safely ignored! However, **error messages** are a problem as these stop the installation process. You can find some solutions to common errors further below.

&nbsp;

#### Solutions to Common Installation Errors:

&nbsp;

>`Installation failed: 'exdir' does not exist`

This usually means the R workspace directory is not writable. Try the following before installing MetaboMate:

  * Start R / RStudio as an admin: open the program with a right-click and then select the open as admin option
  * Change the location of the current workspace to a writable one. E.g., create a new folder in the 'My Documents' directory and then navigate to this folder using RStudio's 'Set working directory' option (Session tab).

&nbsp;

>`A dependency package is not installed`

Like most R packages, MetaboMate depends on a few already existing R packages, some of them are not available via CRAN but the Bioconductor repository. It is likely that Bioconductor packages require manuall installation before you can install MetaboMate. To find out which dependency packages are missing, check the error message for the phrase similar to this: '[some package name] not found'. Once you identified the required package, install it from [Bioconductor](https://www.bioconductor.org/install/). Installation from Bioconductor is very straighforward, each Bioconductor package has a webpage (use Google to find it) which lists R package installatoin code that can be pasted directly into the R console.


&nbsp;


# Tutorials

The following data analysis workflows are available:

* [Import of 1D NMR spectra, quality control and data pre-processing](https://kimsche.github.io/MetaboMate/articles/Imps.html)
* [Mutlivariate statistical analysis using PCA and O-PLS](https://kimsche.github.io/MetaboMate/articles/MVA.html)
* Biomarker identification with STOCSY and STORM

&nbsp;

Although not essential, I recommend to use [RStudio](https://www.rstudio.com) for the tutorials, rather than simply an R console. RStudio is free and an open-source integrated development environment for R. The main pros of using RStudio include easy management of different projects, highlighting of R code syntax and tools for plotting, history and debugging. Simply put, it makes working with R a lot more efficient.

&nbsp;

**Don't be shy and [send me your feedback](mailto:tkimhofer@gmail.com)!**
&nbsp;

&nbsp;



